// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BanIP(arg1, arg2) {
  return window['go']['main']['App']['BanIP'](arg1, arg2);
}

export function Connect(arg1) {
  return window['go']['main']['App']['Connect'](arg1);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function GetBans(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['GetBans'](arg1, arg2, arg3, arg4, arg5);
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetPeers() {
  return window['go']['main']['App']['GetPeers']();
}

export function GetStats() {
  return window['go']['main']['App']['GetStats']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function IsConnected() {
  return window['go']['main']['App']['IsConnected']();
}

export function ListProfiles() {
  return window['go']['main']['App']['ListProfiles']();
}

export function SaveProfile(arg1) {
  return window['go']['main']['App']['SaveProfile'](arg1);
}

export function SubscribeLogs(arg1) {
  return window['go']['main']['App']['SubscribeLogs'](arg1);
}

export function UnbanIP(arg1) {
  return window['go']['main']['App']['UnbanIP'](arg1);
}

export function UnsubscribeLogs() {
  return window['go']['main']['App']['UnsubscribeLogs']();
}
