// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {connection} from '../models';
import {mgmt} from '../models';

export function BanIP(arg1:string,arg2:string):Promise<void>;

export function Connect(arg1:connection.Profile):Promise<void>;

export function DeleteProfile(arg1:string):Promise<void>;

export function Disconnect():Promise<void>;

export function GetBans(arg1:number,arg2:number,arg3:string,arg4:string,arg5:boolean):Promise<mgmt.BansResult>;

export function GetLogs():Promise<Array<string>>;

export function GetPeers():Promise<mgmt.PeersResult>;

export function GetStats():Promise<mgmt.StatsResult>;

export function GetStatus():Promise<mgmt.StatusResult>;

export function IsConnected():Promise<boolean>;

export function ListProfiles():Promise<Array<connection.Profile>>;

export function SaveProfile(arg1:connection.Profile):Promise<void>;

export function SubscribeLogs(arg1:string):Promise<void>;

export function UnbanIP(arg1:string):Promise<void>;

export function UnsubscribeLogs():Promise<void>;
